import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Footer from '../components/Footer';
import Header from '../components/Header';

export default function Home() {
  return (
    <div className={styles.container} data-theme="fantasy">
      <Head>
        <title>Wallets Connect Demo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <div class="hero min-h-screen bg-base-200">
        <div class="hero-content flex-col lg:flex-row-reverse">
          <img src="https://placeimg.com/260/400/arch" class="max-w-sm rounded-lg shadow-2xl" />
          <div>
            <h1 class="text-5xl font-bold">Wallets Connect Demo!</h1>
            <p class="py-6">This is wallet connect demo page created by ayden lee.If you get any problems when using this demo, feel free to connect me!</p>
            <label for="my-modal" class="btn btn-primary modal-button">Get Started</label>
          </div>
        </div>
      </div>

      <input type="checkbox" id="my-modal" class="modal-toggle" />
      <div class="modal">
        <div class="modal-box">
          <h3 class="font-bold text-lg">Congratulations random Internet user!</h3>
          <p class="py-4">Click the connect button on the top of this page!</p>
          <div class="modal-action">
            <label for="my-modal" class="btn">Yay!</label>
          </div>
        </div>
      </div>

      <Footer />
    </div >
  )
}
